config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :trainers
  post '/client_workouts/find' => 'client_workouts#search'
  resources :client_workouts
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    validates :Name, :Address, :Current_weight, :Height, :Gender, :Email, presence: true
    validates :Current_weight, :Height, numericality:true
end

app/models/client_workout.rb
class ClientWorkout < ApplicationRecord
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    validates :Name, :Address, :Current_weight, :Height, :Gender, :Email, presence: true
    validates :Current_weight, :Height, numericality:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/client_workouts_controller.rb
class ClientWorkoutsController < ApplicationController
  before_action :set_client_workout, only: [:show, :edit, :update, :destroy]

  # GET /client_workouts
  # GET /client_workouts.json
  def index
    @client_workouts = ClientWorkout.all
  end

  # GET /client_workouts/1
  # GET /client_workouts/1.json
  def show
  end

  # GET /client_workouts/new
  def new
    @client_workout = ClientWorkout.new
  end

  # GET /client_workouts/1/edit
  def edit
  end

  # POST /client_workouts
  # POST /client_workouts.json
  def create
    @client_workout = ClientWorkout.new(client_workout_params)

    respond_to do |format|
      if @client_workout.save
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully created.' }
        format.json { render :show, status: :created, location: @client_workout }
      else
        format.html { render :new }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

def search
    puts params[:search_string]
    @cname = ClientWorkout.where(client_name: params[:search_string])
end



  # PATCH/PUT /client_workouts/1
  # PATCH/PUT /client_workouts/1.json
  def update
    respond_to do |format|
      if @client_workout.update(client_workout_params)
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_workout }
      else
        format.html { render :edit }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_workouts/1
  # DELETE /client_workouts/1.json
  def destroy
    @client_workout.destroy
    respond_to do |format|
      format.html { redirect_to client_workouts_url, notice: 'Client workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_workout
      @client_workout = ClientWorkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_workout_params
      params.require(:client_workout).permit(:client_name, :trainer, :duration_mins, :date_of_workout, :paid_amount)
    end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:Name, :Address, :Current_weight, :Height, :Gender, :Email)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:Name, :Address, :Current_weight, :Height, :Gender, :Email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_workouts_helper.rb
module ClientWorkoutsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/client_workouts/_form.html.erb
<%= form_with(model: client_workout, local: true) do |form| %>
  <% if client_workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_workout.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

      <ul>
      <% client_workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :trainer %>
    <%= form.text_field :trainer %>
  </div>

  <div class="field">
    <%= form.label :duration_mins %>
    <%= form.number_field :duration_mins %>
  </div>

  <div class="field">
    <%= form.label :date_of_workout %>
    <%= form.date_select :date_of_workout %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.text_field :paid_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_workouts/edit.html.erb
<h1>Editing Client Workout</h1>

<%= render 'form', client_workout: @client_workout %>

<%= link_to 'Show', @client_workout %> |
<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Workouts</h1>



<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_workouts.each do |client_workout| %>
      <tr>
        <td><%= client_workout.client_name %></td>
        <td><%= client_workout.trainer %></td>
        <td><%= client_workout.duration_mins %></td>
        <td><%= client_workout.date_of_workout %></td>
        <td><%= client_workout.paid_amount %></td>
        <td><%= link_to 'Show', client_workout %></td>
        <td><%= link_to 'Edit', edit_client_workout_path(client_workout) %></td>
        <td><%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Workout', new_client_workout_path %>

app/views/client_workouts/new.html.erb
<h1>New Client Workout</h1>

<%= render 'form', client_workout: @client_workout %>

<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/search.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @cname[0].client_name %></h1>


<table>
  <thead>
    <tr>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cname.each do |client_workout| %>
      <tr>
        <td><%= client_workout.trainer %></td>
        <td><%= client_workout.duration_mins %></td>
        <td><%= client_workout.date_of_workout %></td>
        <td><%= client_workout.paid_amount %></td>
        <td><%= link_to 'Show', client_workout %></td>
        <td><%= link_to 'Edit', edit_client_workout_path(client_workout) %></td>
        <td><%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Workout', new_client_workout_path %>

app/views/client_workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @client_workout.client_name %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @client_workout.trainer %>
</p>

<p>
  <strong>Duration mins:</strong>
  <%= @client_workout.duration_mins %>
</p>

<p>
  <strong>Date of workout:</strong>
  <%= @client_workout.date_of_workout %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @client_workout.paid_amount %>
</p>

<%= link_to 'Edit', edit_client_workout_path(@client_workout) %> |
<%= link_to 'Back', client_workouts_path %>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_area :Address %>
  </div>

  <div class="field">
    <%= form.label :Current_weight %>
    <%= form.number_field :Current_weight %>
  </div>

  <div class="field">
    <%= form.label :Height %>
    <%= form.number_field :Height %>
  </div>

  <div class="field">
    <%= form.label :Gender %>
    <%= form.text_field :Gender %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.Name %></td>
        <td><%= client.Address %></td>
        <td><%= client.Current_weight %></td>
        <td><%= client.Height %></td>
        <td><%= client.Gender %></td>
        <td><%= client.Email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.Name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.Address %>
</p>

<p>
  <strong>Current weight:</strong>
  <%= @client.Current_weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @client.Height %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @client.Gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.Email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyville</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= form_tag"/client_workouts/find" do%>
        <%= text_field_tag :search_string %>
        <%= submit_tag :search%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_area :Address %>
  </div>

  <div class="field">
    <%= form.label :Current_weight %>
    <%= form.number_field :Current_weight %>
  </div>

  <div class="field">
    <%= form.label :Height %>
    <%= form.number_field :Height %>
  </div>

  <div class="field">
    <%= form.label :Gender %>
    <%= form.text_field :Gender %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Current weight</th>
      <th>Height</th>
      <th>Gender</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.Name %></td>
        <td><%= trainer.Address %></td>
        <td><%= trainer.Current_weight %></td>
        <td><%= trainer.Height %></td>
        <td><%= trainer.Gender %></td>
        <td><%= trainer.Email %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.Name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @trainer.Address %>
</p>

<p>
  <strong>Current weight:</strong>
  <%= @trainer.Current_weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @trainer.Height %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @trainer.Gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.Email %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>